# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.16.x'
    - name: Use cmake
      run: |
        cmake --version
        # mkdir Git_Action_Cmake_2_build
        # cd Git_Action_Cmake_2_build
        # cmake ../Git_Action_Cmake_2
        # cmake --build .
        # Git_Action_Cmake_2
        # cmake --build .
        # Git_Action_Cmake_2
        echo CMakeLists.txt
